### ISSUE TITLE
Update/remove documentation that came from previous groups

### ISSUE THREAD

**Issue by wkmeijer** [klikooo/CS4160-trustchain-android#13]
There is some documentation, e.g. code coverage from previous groups still in the repo. This can be removed or updated to reflect the state of this repo.

Note: don't forget to also add screenshots where relevant.
Working branch for this issue is **13_update_documents**

- [x]  Update https://readthedocs.org/projects/trustchain-android/ so it reflects the current state of the documentation
- [x] (R) Add documentation about passport scanning
- [x] Add documentation about offline block signing (some of this is already in the offline signing branch)
- [x] Add documentation about claim and attestations for our implementation (synctext linked to [this](https://tools.ietf.org/html/draft-pouwelse-trustchain-01#section-4.2))
- [x] (R) Add documentation about the chainexplorer
- [x] Update [contact page](https://github.com/klikooo/CS4160-trustchain-android/blob/master/docs/source/contact.rst)
- [x] (WKM) Update [create-block page](https://github.com/klikooo/CS4160-trustchain-android/blob/master/docs/source/creating-block.rst)
- [x] (WKM) Update [database page](https://github.com/klikooo/CS4160-trustchain-android/blob/master/docs/source/database.rst)
- [x] (WKM) Update [inbox page](https://github.com/klikooo/CS4160-trustchain-android/blob/master/docs/source/inbox.rst)
- [x] (R) Update [installation instructions page](https://github.com/klikooo/CS4160-trustchain-android/blob/master/docs/source/installation-instructions.rst)
- [x] (WKM) Update [introduction](https://github.com/klikooo/CS4160-trustchain-android/blob/master/docs/source/introduction.rst)
- [x] (WKM) Update [protocolbuffers page](https://github.com/klikooo/CS4160-trustchain-android/blob/master/docs/source/protocolbuffers.rst)
- [x] (WKM) Update [trustchain page](https://github.com/klikooo/CS4160-trustchain-android/blob/master/docs/source/trustchain.rst) (the dispersy part can be removed I think)
- [x] (WKM) Update [readme](https://github.com/klikooo/CS4160-trustchain-android/blob/master/README.md) remove "report" from other groups.

**Comment by wkmeijer** [comment]
@klikooo Could you do the part about claim and attestations? I think it would be good talk for a bit about the troubles with getting zero knowledge proofs working on android.

**Comment by klikooo** [comment]
@wkmeijer will do
